apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: secret-docker
      containers:
      - name: gopher-api
        image: ghcr.io/nozadewz/workshop:1e0e309d46ccf891da141f5ab06d8c5116afb659
        imagePullPolicy: Always
        ports:
        - containerPort: 1323
        envFrom:
          - configMapRef:
              name: app-env-config
          - secretRef:
              name: secret-config
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1323
            httpHeaders:
            - name: Authorization
              value: 'basic YWRtaW46c2VjcmV0'
          initialDelaySeconds: 3
          periodSeconds: 60

